/**
 * Threshold types and pure helpers — NO database, NO `server-only`.
 *
 * Split out from `thresholds.ts` because the public registry table is a client
 * component: it renders bands and needs `formatBand`. Importing that from a
 * module marked `server-only` fails the build, and the fix is not to drop the
 * marker (the loaders genuinely must not reach the browser — they hold a
 * service-role client) but to separate the pure half.
 *
 * Nothing here touches Supabase. Everything here is safe on either side.
 */

export type ThresholdBasis =
  | "FAO_REFERENCE"
  | "CITRUS_REFERENCE"
  | "POMELO_MEKONG_REFERENCE"
  | "SENSOR_QUALITY"
  | "DEVICE_HEALTH"
  | "SITE_CALIBRATED"
  | "LEGACY_UNVALIDATED";

export type ValidationStatus = "REFERENCE" | "PILOT" | "OPERATIONAL" | "SITE_VALIDATED";

export type ThresholdSeverity = "normal" | "watch" | "warning" | "critical" | "low_confidence";

export interface ThresholdRow {
  id: string;
  metric_key: string;
  quantity: string;
  unit: string;
  threshold_value: number | null;
  upper_value: number | null;
  comparison: "above" | "below" | "between" | "outside";
  severity: ThresholdSeverity;
  basis: ThresholdBasis;
  source_title: string | null;
  source_url: string | null;
  source_locator: string | null;
  scope: string | null;
  validation_status: ValidationStatus;
  is_active: boolean;
  notes: string | null;
  effective_from: string | null;
}

export interface SoilWaterModel {
  station_id: string;
  field_capacity_pct: number;
  permanent_wilting_point_pct: number;
  management_allowed_depletion_pct: number;
  /** Generated by Postgres from the three above — never written directly. */
  irrigation_trigger_pct: number;
  source_note: string | null;
}

export interface ApplicationProfile {
  key: "ORCHARD" | "RICE_SHRIMP" | "AWD_MRV";
  title: string;
  description: string;
  available_metrics: string[];
  needed_metrics: string[];
  available_thresholds: string[];
  unvalidated_thresholds: string[];
  maturity: "PILOT" | "BUILDING_EVIDENCE" | "FUTURE";
}

export interface WaterLevelContext {
  station_id: string;
  sensor_datum_cm: number | null;
  shore_bank_elevation_cm: number | null;
  critical_infrastructure_elevation_cm: number | null;
  survey_note: string | null;
  validation_status: "PILOT" | "OPERATIONAL" | "SITE_VALIDATED";
}

/**
 * The thresholds that may actually colour something, for one quantity.
 *
 * Matches on QUANTITY, not metric_key — the whole point of the distinction.
 * Returns only active rows, so a caller cannot accidentally evaluate a
 * reference figure by forgetting to filter.
 */
export function activeThresholdsFor(rows: ThresholdRow[], quantity: string): ThresholdRow[] {
  return rows.filter((r) => r.quantity === quantity && r.is_active);
}

/**
 * The severity a value earns, or null for "no opinion".
 *
 * Returning null is the common case and the correct one for most metrics in
 * this system. It means no ACTIVE threshold covers this quantity — not that
 * the reading is fine.
 */
export function resolveSeverity(
  rows: ThresholdRow[],
  quantity: string,
  value: number | null,
): { severity: ThresholdSeverity; row: ThresholdRow } | null {
  if (value === null || !Number.isFinite(value)) return null;

  const RANK: Record<ThresholdSeverity, number> = {
    normal: 0,
    low_confidence: 1,
    watch: 2,
    warning: 3,
    critical: 4,
  };

  let worst: { severity: ThresholdSeverity; row: ThresholdRow } | null = null;

  for (const row of activeThresholdsFor(rows, quantity)) {
    const lower = row.threshold_value;
    const upper = row.upper_value;
    if (lower === null) continue;

    let hit = false;
    switch (row.comparison) {
      case "above":
        hit = value > lower;
        break;
      case "below":
        hit = value < lower;
        break;
      case "between":
        hit = upper !== null && value >= lower && value <= upper;
        break;
      case "outside":
        hit = upper !== null && (value < lower || value > upper);
        break;
    }

    if (hit && (!worst || RANK[row.severity] > RANK[worst.severity])) {
      worst = { severity: row.severity, row };
    }
  }

  return worst;
}

/**
 * A public, informational reading of sourced rows that are deliberately not
 * active operational thresholds. This never creates an alert or action; it
 * merely lets Monitoring say where a compatible measurement sits relative to
 * a published reference or pilot band.
 */
export function resolveReferenceSeverity(
  rows: ThresholdRow[],
  quantity: string,
  value: number | null,
): { severity: ThresholdSeverity; row: ThresholdRow } | null {
  if (value === null || !Number.isFinite(value)) return null;

  const RANK: Record<ThresholdSeverity, number> = {
    normal: 0,
    low_confidence: 1,
    watch: 2,
    warning: 3,
    critical: 4,
  };
  let worst: { severity: ThresholdSeverity; row: ThresholdRow } | null = null;

  for (const row of rows) {
    if (row.quantity !== quantity || row.is_active || row.threshold_value === null) continue;
    const lower = row.threshold_value;
    const upper = row.upper_value;
    const hit = row.comparison === "above"
      ? value > lower
      : row.comparison === "below"
        ? value < lower
        : row.comparison === "between"
          ? upper !== null && value >= lower && value <= upper
          : upper !== null && (value < lower || value > upper);
    if (hit && (!worst || RANK[row.severity] > RANK[worst.severity])) worst = { severity: row.severity, row };
  }
  return worst;
}

/**
 * A row's band as a reader reads it.
 *
 * Deliberately SYMBOLIC and language-free — `<`, `>`, an en-dash range, and
 * `∉` for "outside". Display text belongs in lib/i18n; a band is notation, and
 * notation does not need translating. The alternative was a Vietnamese word in
 * a lib module, which is exactly what the i18n guard exists to catch.
 */
export function formatBand(row: ThresholdRow): string {
  const v = row.threshold_value;
  const u = row.upper_value;
  const unit = row.unit === "pH" ? "" : ` ${row.unit}`;
  switch (row.comparison) {
    case "above":
      return `> ${v}${unit}`;
    case "below":
      return `< ${v}${unit}`;
    case "between":
      return `${v} – ${u}${unit}`;
    case "outside":
      return `∉ ${v} – ${u}${unit}`;
  }
}
